import type { Metadata } from "next";
import "./globals.css";
import { GlassToolbar } from "@/system/recipes/GlassToolbar";

export const metadata: Metadata = {
  title: "Rum River Glass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlassToolbar />
        <div style={{ paddingLeft: "var(--glass-toolbar-offset, var(--glass-toolbar-rail-width, 78px))" }}>
          {children}
        </div>
      </body>
    </html>
  );
}